### ISSUE TITLE
Initialize project

### ISSUE THREAD

**Issue by andre4meister** [RomanKalitovskiy/django_ts#1]
# Initializing project
**bold**
_italic_
|1|2|
|---|---|
|testing|markdown|

![Screenshot 2022-07-23 at 01 19 11](https://user-images.githubusercontent.com/85457818/180575851-f3ed8e15-7870-4ffd-9882-2e4e80d7e12a.png)

**Comment by RomanKalitovskiy** [comment]
fds

> fdsfs

`code`

[test](https://translate.google.com/)

- fdsf
- dsfsdf
- dsfdsf

1. 123
2. fdsfds
3.1 dads

- [ ] fghfgh

- [ ] fghfgh

- [ ] hgfhg
@andre4meister @popovycj @RomanKalitovskiy

**Comment by RomanKalitovskiy** [comment]
#2

**Comment by RomanKalitovskiy** [comment]
close
