### ISSUE TITLE
Add needed dependencies

### ISSUE THREAD

**Issue by andre4meister** [RomanKalitovskiy/django_ts#4]

**Comment by RomanKalitovskiy** [comment]
```js
{
  const a = 10;
}
```

**Comment by RomanKalitovskiy** [comment]
```json
{
  "firstName": "John",
  "lastName": "Smith",
  "age": 25
}
```

**Comment by RomanKalitovskiy** [comment]
```python
print(10)
```

**Comment by RomanKalitovskiy** [comment]
Here's a simple footnote,[^1] and here's a longer one.[^bignote]

[^1]: This is the first footnote.

[^bignote]: Here's one with multiple paragraphs and code.

    Indent paragraphs to include them in the footnote.

    `{ my code }`

    ```js
    { test: 16 }
    ```

    Add as many paragraphs as you like.

**Comment by RomanKalitovskiy** [comment]
### My Great Heading {#heading-ids}

a

lot

of

text

to

test

if

the

heading

works

[Link to a Heading](#heading-ids)

**Comment by RomanKalitovskiy** [comment]
> ### My Great Heading {#heading-ids}
> a
> 
> lot
> 
> of
> 
> text
> 
> to
> 
> test
> 
> if
> 
> the
> 
> heading
> 
> works
> 
> [Link to a Heading](#heading-ids)

NO

**Comment by RomanKalitovskiy** [comment]
~~The world is flat.~~ We now know that the world is round.

**Comment by RomanKalitovskiy** [comment]
- [x] Write the press release
- [ ] Update the website
- [ ] Contact the media

**Comment by RomanKalitovskiy** [comment]
I need to highlight these ==very important words==.

**Comment by RomanKalitovskiy** [comment]
> I need to highlight these ==very important words==.

Do not work

**Comment by RomanKalitovskiy** [comment]
H<sub>2</sub>O

H~2~O

**Comment by RomanKalitovskiy** [comment]
X<sup>2</sup>

**Comment by RomanKalitovskiy** [comment]
text
***
text
---
text
___
text

**Comment by RomanKalitovskiy** [comment]
Try to put a blank line before...

---

...and after a horizontal rule.

**Comment by RomanKalitovskiy** [comment]
Without blank lines, this would be a heading.
---
Don't do this!

**Comment by RomanKalitovskiy** [comment]
My favorite search engine is [Duck Duck Go](https://duckduckgo.com "The best search engine for privacy").

**Comment by RomanKalitovskiy** [comment]
<img src="https://user-images.githubusercontent.com/85457818/181190021-e487dae1-c09e-412f-832a-a1af429fe8dd.png" width="2000" height="300">

**Comment by RomanKalitovskiy** [comment]
\* Without the backslash, this would be a bullet in an unordered list.
* bullet in an unordered list.

**Comment by RomanKalitovskiy** [comment]
This **word** is bold. This <em>word</em> is italic.

**Comment by RomanKalitovskiy** [comment]
> Dorothy followed her through many of the beautiful rooms in her castle.
>
>> The Witch bade her clean the pots and kettles and sweep the floor and keep the fire fed with wood.

**Comment by RomanKalitovskiy** [comment]
1. First item
2. Second item
3. Third item
    1. Indented item
    2. Indented item
4. Fourth item

**Comment by RomanKalitovskiy** [comment]
- First item
- Second item
- Third item
    - Indented item
    - Indented item
- Fourth item

**Comment by RomanKalitovskiy** [comment]
* This is the first list item.
* Here's the second list item.
I need to add another paragraph below the second list item.
* And here's the third list item.
